### PR TITLE
(GH-241) Add ability to break build when issues exist

### LINKED ISSUE #241: Add build breaking based on issues
It would be nice to have the option to have build breaking if certain conditions for issues are met (e.g. issues exist, or issues of a certain severity exist)

### PR DESCRIPTION
**Pull request by AdmiringWorm**
This pull request adds the ability to break when there have
been found issues with of the the tools used to identify
those. As well as optionally only take into account
when a issue is of a specified priority.

resolves #241

### CODE REVIEW

**Comment by AdmiringWorm** [comment]
Running integration tests against this PR, I expect them all to fail (otherwise the changes are a failure).

**Comment by AdmiringWorm** [comment]
> You currently break based on priority. In practice it might be useful to have the option to define different build breaking conditions for the different type of issues (e.g. break on warnings in MsBuild, but on errors for markdownlint). You can use IIssue.ProviderType and the corresponding alias per issue provider for this (e.g. MsBuildIssuesProviderTypeName)

I do agree that would be better, but it would include a complexity level I would not be comfortable with implementing inside Cake.Recipe (mostly due to how little I believe that would be used, vs the cost of implementing it).

> On a more general level: Cake.Issues.Recipe might be a better place to have this implemented, since in this case all issue stuff is in one place, if breaking changes happen this can be fixed in Cake.Issues.Recipe and doesn't require also changes in Cake.Recipe and the code can be reused by people usinc Cake.Issues.Recipe directly without Cake.Recipe.

I don't disagree with that all, it probably would be better to be implemented in Cake.Issues.Recipe.

**Comment by gep13** [comment]
@AdmiringWorm what are your thoughts about moving forward with this?  @pascalberger has created an issue for adding this into Cake.Issues.Recipe.  Should we wait on that being implemented, or should we merge this, and then switch once implemented in Cake.Issues.Recipe?

**Comment by AdmiringWorm** [comment]
@gep13 let us just wait for it to be implemented upstream, once it has I can change this PR to enable it instead.

**Comment by AdmiringWorm** [comment]
Closing the draft, I don't want to have it open anymore :smile: 
Could always re-open it when such a feature is available.

**Pull request closed without merging**
