### PR TITLE
(GH-92) Create reports for MsBuild warnings

### LINKED ISSUE #92: Add Cake.CodeAnalysisReporting
Create reports for MsBuild warnings using Cake.CodeAnalysisReporting.

### PR DESCRIPTION
**Pull request by pascalberger**
Creates reports for MsBuild warnings using Cake.CodeAnalysisReporting.

Fixes #92

### CODE REVIEW

**Comment by gep13** [comment]
@pascalberger so, I have been giving this some thought, and I think we need some changes to what you have here.  Let me try to explain, and see if you agree.

I think that the new work of performing the code analysis reporting should be added as a new sub-task here:

https://github.com/cake-contrib/Cake.Recipe/blob/develop/Cake.Recipe/Content/resharper.cake#L96

In the same way that the DupFinder and InspectCode analyses are done.  With that done, I think the name of that file needs to change to more accurately reflect what it is being used for.  Once that is done, we should be able to put the similar Criteria in place to allow the end-user to decide whether or not to perform the analysis or not.

Does your addin return an error if problems are found?  i.e. can it stop the build?  If so, it might be good to use a similar `ReportError` to open the report that was generated.

What do you think?

**Comment by pascalberger** [comment]
@gep13 Sounds good to me. I'll update the PR

**Comment by pascalberger** [comment]
@gep13 I've moved the code to a sub-task with the other code analysing task. 

I didn't have added any criteria yet to disable creation of the reports yet. How can the other analyzing tasks be disabled? Looking at the code it seems like they always run.

Since the plugin doesn't actually run the code analysis (this is done during build) but only creates reports, it currently didn't report back if any warnings were found or not. The reports are currently always build even though there are no warnings available. I think this could be enhanced in the plugin to only create the report if warnings exist in the MsBuild log and add a setting if build should break if warnings were found (but IMHO this should be the job ob the build executing the code analysis and not of the addin creating the reports)

**Comment by gep13** [comment]
@pascalberger apologies, I thought I had added in build parameters to control whether or not DupFinder and InspectCode were executed, but it looks like I haven't added that step yet 😢

**Comment by gep13** [comment]
@pascalberger hmmm...

Ok, thinking about this some more...  If the build doesn't succeed, this task will never execute.  Would you want this step to occur in the Finally section of the Build Task instead of here?  That way, it would be ran always, and can provide additional information about the build failure?

**Comment by pascalberger** [comment]
@gep13 See #94

**Pull request merged**
