### PR TITLE
(docs) Updates to requirements page

### PR DESCRIPTION
**Pull request by AdmiringWorm**
Among the changes in this pr there are mainly updates to styling on the requirements page.
Additionally there is now additional documentation regarding installing mono (and .NET Core) on POSIX systems (slit into tabs).
I also made some changes to the style of the tables to have the content centered (the centering in the markdown don't matter, this was just done by markdownlint)
as well as add additional information of possibly a .NET Core requirement on Winows as well.

### CODE REVIEW

**Review by gep13 — APPROVED** [review]
LGTM!

**Comment by gep13** [comment]
@AdmiringWorm thank you very much for doing this, looks great to me!

Quick question.. the two spaces that you changed to one, is that a rule that you have enabled within markdownlint?  Would be happy to have that added so that it shows up as a problem, as I don't remember seeing that as an issue in my setup.

**Comment by AdmiringWorm** [comment]
@gep13 I have not enabled/disabled any rules myself.
But as I am using the [markdownlint vscode extension](https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint) it is possible that it has some custom rules it do by itself (or it could be the [prettier extension](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) I am using).

**Comment by gep13** [comment]
Hmm, I have the same two extensions installed, but I don't recall seeing the double space listed as a Problem:

image

At school, I had the usage of two spaces between sentences drummed into me, and it looks like this is something that I will have to get out of the habit of doing.  If there is a setting that can help with this, then I would love to know what it is.

**Comment by AdmiringWorm** [comment]
Just checked myself, I don't get any warning when having two spaces after the dot.
It seems to be just prettier that decides to format it automatically (I have format on save enabled).

> At school, I had the usage of two spaces between sentences drummed into me,

I had the opposite, and I got scolded every time I used two spaces between sentences (no matter if I wrote in Norwegian, or English).

**Comment by gep13** [comment]
Hmmm, so I didn't have the format on save setting on, but now I do, but it still isn't removing the double space.

Do you have any other extensions that might be tidying this up?

**Comment by gep13** [comment]
Never mind... I figured it out.  Seems like I have multiple formatters installed, and I had to select prettier to associate itself with markdown files.  This got things working.  Thanks!

**Pull request merged**
