### PR TITLE
Updated versions.

### PR DESCRIPTION
**Pull request by vkbishnoi**
@gep13 / @AdmiringWorm : Can you please review this pull request. 
My another pull request for "Cake.Protocolbufs" is failing tests because of this (I think) and because of that my another pull request for "Cake.Newman" is also stuck.

### CODE REVIEW

**Comment by gep13** [comment]
@vkbishnoi we already have an open Pull Request that is starting to increment the version numbers:

https://github.com/cake-contrib/Cake.Recipe/pull/208

This is in line with the ongoing work that is being tracked in this issue:

https://github.com/cake-contrib/Cake.Recipe/issues/207

Once all the dependent addin's have been updated, we will do some testing of all the components, and then update the version numbers.

As a result, for now, I am going to close this Pull Request.

In order to proceed, I would recommend any addin that is using Cake.Recipe be pinned to using 0.25.0 of Cake for doing the build.  **NOTE:** This will not prevent the addin from referencing a higher version of Cake/Cake.Common, for example 0.26.x.

**Comment by vkbishnoi** [comment]
@gep13 : I know there is already one pull request opened to update versions. Since the author of that pull request is not responding hence I thought of quickly updating the versions and raised another pull request with an intention of updating this repo quickly.

**Comment by gep13** [comment]
@vkbishnoi I wouldn't go as far as to say that an elapse of 19 hours is not responding.  As mentioned in that PR, I won't be pulling in any changes until all Cake.Recipe dependencies have been updated.  There are still two that fall into this.  Once they are done, I am sure that @nmbro will be in a position to update his PR.

**Comment by vkbishnoi** [comment]
@gep13 : Please don't get me wrong but IMO, the fun of working with open source and git is to have developers contributing round the clock. I don't think it matter much whether it's pull request from @nmbro or from me or someone else which gets approved and become part of master. We all are trying to help. I am trying to help.
There are 2 more which needs version update, were not known to me (maybe I overlooked), sorry for that. Let's wait then.

**Comment by gep13** [comment]
>@vkbishnoi said...
Please don't get me wrong but IMO, the fun of working with open source and git is to have developers contributing round the clock. I don't think it matter much whether it's pull request from @nmbro or from me or someone else which gets approved and become part of master. We all are trying to help. I am trying to help.
There are 2 more which needs version update, were not known to me (maybe I overlooked), sorry for that. Let's wait then.

The other PR references the open issue where the outdated addin's are being tracked:

https://github.com/cake-contrib/Cake.Recipe/issues/207

To an extent, I agree with what you are saying, however, the main thing that I was trying to avoid by closing this PR was duplication of effort.  Both this PR, and/or the other one, will need to be updated when the upstream addins are updated.  That request has already been made in the other PR, so there is/was no point in repeating the same effort here.

**Pull request closed without merging**
