### PR TITLE
GH194: Fixing MSTest Issues

### PR DESCRIPTION
**Pull request by phillipsj**
Just the start.

### CODE REVIEW

**Comment by gep13** [comment]
Relates to #194

**Comment by gep13** [comment]
@phillipsj where did we get to with this?

**Comment by phillipsj** [comment]
@gep13 I got pulled away from the project that had me investigating.  The change I made fixes the initial error and it is now an error trying to locate the tool.

**Comment by gep13** [comment]
@phillipsj do you think we should pull this in then?  And circle back around when you are looking at this again?

**Comment by phillipsj** [comment]
Yep, it would move it past that one issue.

**Comment by gep13** [comment]
@phillipsj perfect.  I will leave the original issue open, and you can come back to it when you have some time.  Thanks again!

**Pull request merged**
