### PR TITLE
(GH-702) added documentation for TeamCity

### LINKED ISSUE #702: TeamCity documentation is missing under CI-Systems
https://cake-contrib.github.io/Cake.Recipe/docs/ci-systems/teamcity still reads

```
This documentation is currently missing.
```

### PR DESCRIPTION
**Pull request by nils-a**
Seems exposing `vcsroot.branch` is required for Cake.Recipe to run.

fixes #702

### CODE REVIEW

**Comment by gep13** [comment]
@nils-a thanks for this, really appreciate it!

Does this configuration go into a file in the repository, or does this go into a build configuration within TeamCity?  Historically, TeamCity was very much UI driven.  How would I take have you have provided here and get it _into_ a build?

**Comment by nils-a** [comment]
@gep13 no, that's the DSL, as displayed in TeamCity - as far as I see the DSL can be edited in the UI but not checked into the repository like the others. (Probably should mention that, though.)

**Comment by pascalberger** [comment]
TeamCity can store its configration in a VCS, see https://www.jetbrains.com/help/teamcity/storing-project-settings-in-version-control.html. But I would suggest to keep it to the user how he uses TeamCity (through UI, with settings stored in XML, with settings stored in Kotlin)

**Comment by nils-a** [comment]
@gep13 @pascalberger I have added a sentence to explain the exported Kotlin DSL. 

Should we better use screenshots to document this?

**Comment by gep13** [comment]
@nils-a screenshots never hurt, so if you wanted to add some here, I certainly wouldn't say no 😄

**Comment by nils-a** [comment]
@gep13 added a textual guideline thru the TeamCity-UI, including two screenshots. (and I was able to add the `img-responsive`-calass thanks the video from the week before 😃 )

**Review by gep13 — APPROVED** [review]
LGTM!

**Comment by gep13** [comment]
@nils-a thanks for getting this documented!

**Pull request merged**
