### PR TITLE
removes <ActionTask> from tasks.cake

### PR DESCRIPTION
**Pull request by Mmmolin**
FIxes Recipe for Cake 0.28.0 and updates repo to use 0.28.0

### CODE REVIEW

**Comment by devlead** [comment]
Relates to #207

**Comment by JenasysDesign** [comment]
@Mmmolin @devlead @mholo65   what's holding up the merge of this PR. LGTM

**Comment by gep13** [comment]
@JenasysDesign this can't be pulled in until this issue is completed:

https://github.com/cake-contrib/Cake.Recipe/issues/207

i.e. we can't support 0.28.0, until we first ensure that all the dependent addin's work for 0.26.0.

**Comment by gep13** [comment]
@Mmmolin Thank you for taking the time to do this!

**Comment by gep13** [comment]
With this merged in... every project that is using Cake.Recipe will now have to start using Cake 0.28.0.

**Pull request merged**
