### PR TITLE
(GH-568) Add support for logging when running .NET Core build

### LINKED ISSUE #568: Create log file when running dotnet build
Currently when running dotnet build through Cake.Recipe, we do not log any output to file.

This seems like it can be done with the following answer on StackOverflow: https://stackoverflow.com/a/48561727
This would be useful to have when reporting issues together with Cake.Issues.Recipe.

This may perhaps apply to dotnet restore, dotnet test, dotnet publish and dotnet package as well.

### PR DESCRIPTION
**Pull request by AdmiringWorm**
This pull request adds support for logging the result of dotnet build to file.

Additionally this log file is passed to Cake.Issues so it can generate a issue report with the warning returned by msbuild.

resolves #568

### CODE REVIEW

**Comment by AdmiringWorm** [comment]
Integration tests passed, artifact report.html can be seen on the appveyor build:

https://ci.appveyor.com/project/AdmiringWorm/cake-recipe-tests/builds/34119388
https://travis-ci.org/github/AdmiringWorm/Cake.Recipe.Tests/builds/708491266

**Comment by gep13** [comment]
@AdmiringWorm lets do this one next :)

**Comment by AdmiringWorm** [comment]
@gep13 on it, currently trying to resolve the merge conflicts

**Comment by gep13** [comment]
@AdmiringWorm 
your changes have been merged, thanks for your contribution 👍

**Pull request merged**
