### PR TITLE
GH204: Allow running GitVersion on non Windows platform

### PR DESCRIPTION
**Pull request by mholo65**

### CODE REVIEW

**Comment by gep13** [comment]
@mholo65 how much have you tested this?

**Comment by mholo65** [comment]
@gep13 I’ve tested locally in Bakery, butvthis particular change was done via GH Web UI.

Basically, builds on non-windows platforms will fail unless it has a `SolutionInfo.cs`. And there’s no extension point allowing me to configure that :worried:

**Comment by mholo65** [comment]
Fixes #204

**Comment by gep13** [comment]
@mholo65 your changes have been merged, thanks for your contribution :+1:

**Pull request merged**
