### PR TITLE
update to cake.incubator 4.0.2, Gitversion to 4.0.1-beta1-58

### PR DESCRIPTION
**Pull request by arturcic**
This PR is needed in order to be able to update to cake 0.33.0. As Cake.Recipe builds with Cake.Recipe we need to update some dependencies first. Another PR will follow

### CODE REVIEW

**Comment by arturcic** [comment]
@gep13 do you mind having a look? I have used the same version of GitVersion as Cake team is using for now

**Comment by AdmiringWorm** [comment]
Personally I think updating Gitversion to 4.0+ could be a bad idea.
Just do to one reason though: It comes with a breaking change (compared to 3.x) when using a configuration file, as well as some some branches is using a different pre-release label.

IMO, a opt-in should rather be implemented instead.

**Comment by gep13** [comment]
@AdmiringWorm you raise a good point.

Making this change does have it's good points though, as it would mean that it could be one less thing that needs a mono dependency, so in theory, it would get us further along the road in terms of that.

@arturcic I think I would suggest holding off on making this change, based on what @AdmiringWorm has stated.  I would really like to get to a release of Cake.Recipe in the near future, which will likely be a 1.0.0 release, and then we can look at pulling in breaking changes like this.

Thoughts?

**Comment by Jericho** [comment]
Just want to point out that there is an automated process that takes care of upgrading addin references that are used by Cake.Recipe. Additionally, this automated process will upgrade the version of Cake used to build Cake.Recipe as soon as all the addins support Cake 0.33.0.

**Comment by arturcic** [comment]
The reason I updated GitVersion is because when I tried updating to cake version 0.33.0 I got this error

image

As far as I understand the Cake team has added verbosity settings or similar https://github.com/cake-build/cake/issues/2141 (have a look at release notes)

**Comment by gep13** [comment]
@arturcic hmmm....

You make a good point... argh!

**Comment by arturcic** [comment]
I could agree that GitVersion should remain 3.6.5 for now, as there are some breaking changes in 4.0+, or even 5.0-beta+. That's why my choice was to use the same version as Cake team uses for now

**Comment by gep13** [comment]
>@AdmiringWorm said...
if the verbosity argument is always passed when calling the gitversion alias, 

As of 0.33.0 of Cake, this is now always passed yes 😢 

There was a quick discussion as to whether or not we should create a GitVersion3 and GitVersion4 aliases, similar to what is done for the likes of NUnit, but I personally don't want to go down that route, and instead, recommend people to update to newest GitVersion.

I think I should look to "finally" getting a finalised release of Cake.Recipe out the door, and then look to bump to 0.33.0 of Cake and support things like newer GitVersion, and then start making some other changes as well, i.e. TypedContext for all tasks, and other improvements.

**Comment by gep13** [comment]
I am going to go ahead and close this PR, in favour of the other two PR's that are raised here:

https://github.com/cake-contrib/Cake.Recipe/pull/333
https://github.com/cake-contrib/Cake.Recipe/pull/339

**Pull request closed without merging**
