### PR TITLE
GH166: Add FrameworkPathOverride when running on Mono

### PR DESCRIPTION
**Pull request by gep13**

### CODE REVIEW

**Comment by gep13** [comment]
@mholo65 @pascalberger @RLittlesII what are your collective thoughts on this one?

Given that I am exposing the entire `MSBuildSettings` and `DotNetCoreBuildSettings` I am tempted to say that we remove `ToolSettings.BuildPlatformTarget`, `ToolSettings.BuildMSBuildToolVersion`, `ToolSettings.MaxCpuCount`, etc, but that is where the breaking change starts to come in.

Thoughts...

**Comment by gep13** [comment]
@mholo65 I am just worried that it will cause confusion if left as is/

**Comment by RLittlesII** [comment]
I agree with @gep13 while it does introduce a breaking change, I would argue breaking now to avoid long term confusion is best.
Can we deprecate the legacy `ToolSettings` so people know that it is going away, and then clean it up later?

**Comment by gep13** [comment]
@RLittlesII @mholo65 so, what were we thinking about this one then?  Should I refactor it further?

**Comment by mholo65** [comment]
@gep13 I'd rather see you expose `DotNetCoreMSBuildSettings` and use that in all `DotNetCoreAliases`. E.g. `DotNetCoreRestore`, `DotNetCoreBuild`, `DotNetCorePublish`, `DotNetCorePack`, etc...

See example on how we do this in Cake here https://github.com/cake-build/cake/blob/develop/build.cake#L23

**Comment by gep13** [comment]
@mholo65 understood. The question was more around whether we should continue to use the old way of doing it, or fully switch to the new way.

**Comment by mholo65** [comment]
@gep13 as long as the old you'd like to remove is also available through `DotNetCoreMSBuildSettings`, I'm fine with the change.

**Comment by RLittlesII** [comment]
@gep13 I think it's the best path forward for the long term.  The breaking change will be immediate though as Cake.Recipe hasn't had a version bump in a while, correct?  I know some cake-contrib repos use prerelease, and could fail on next build.

**Comment by RLittlesII** [comment]
@gep13 How close are we to a resolution on this?  I think this would be helpful in solving my cross platform build issues for MacOS with Cake.Recipe.  Seems like we just need to change `DotNetCoreBuildSettings` to `DotNetCoreMSBuildSettings`?  If you would like help let me know.

**Comment by devlead** [comment]
MSBuildSettings would be lovely, to be able to build on Mac/Linux I added the following code
https://github.com/cake-contrib/Cake.Kudu.Client/blob/e3705fdd3ad9aec662f092c8e8409e5d0676f949/setup.cake#L24-L55

That said adding framwork override is pretty common for multi targeted builds, so perhaps something Recipie should offer an opt-in boolean for.

**Comment by mholo65** [comment]
Now that I've got Cake.Bakery building with Cake.Recipe under Mono I'm pretty sure that I know everything that needs to be done... If you don't mind @gep13 I can take over the PR from here and update it in the next couple of days.

**Comment by gep13** [comment]
You are more than welcome.

I would like to see this done in as backward compatible a way as possible though...

**Comment by mholo65** [comment]
I think we don't even need to expose the `DotNetcoreMSBuildSettings`. Best way could be for `Cake.Recipe` to automatically add `FrameworkPathOverride` if running under Mono.

**Comment by gep13** [comment]
That sounds like a good idea to me!

**Comment by gep13** [comment]
I am not able to approve this, since I created the original PR, but I am going to YOLO it :smile:

**Pull request merged**
