### PR TITLE
(GH-7) Add support for VS Test

### PR DESCRIPTION
**Pull request by Jericho**
Question: does it make sense to have both MS test and VS test? Should I remove cod for MS Test especially since the code for MS test doesn't have support for OpenCover and the new code for VS test does support OpenCover?

### CODE REVIEW

**Comment by Jericho** [comment]
I messed up my branch trying to rebase.

**Comment by gep13** [comment]
From what I understand, there is good reason to have both MSTest and VSTest, as they are used in different places, and serve different purposes.  I can't speak to the differences between them, as I don't use either of them.  But I think it makes sense that they are both supported.

**Comment by gep13** [comment]
@Jericho I have corrected your branch, leaving only the two commits that you have made.

If you delete the local branch that you have, and then checkout it out again, you should be able to continue.  This is required since I did a force push.

The second commit that you have in this branch, is it required?

**Comment by Jericho** [comment]
The second commit is the result of a failed attempt to fix my failed attempt at rebasing my branch. It can be discarded.

**Comment by Jericho** [comment]
Regarding mstest vs vstest: fine, I will leave both in the recipe but one thing intrigues me: how will the recipe know which one to use? Is there a way to indicate that I want VS instead of MS?

**Comment by Jericho** [comment]
oh by the way, I forgot to thank you for fixing my branch!

**Comment by Jericho** [comment]
I figured out how to get rid of the second commit. Now, I see that you made some commits to the develop branch, I need to figure out how to safely rebase without messing up my branch like I did last time!

**Comment by Jericho** [comment]
ok, I think I successfully rebased my branch

**Comment by gep13** [comment]
@Jericho thanks for getting this added!

**Pull request merged**
