### PR TITLE
(GH-581) Remove use of Username/pass for GitHub

### LINKED ISSUE #581: Remove GitHub Password usage
This is replaced pretty much everywhere with using only a token, so this variable is no longer required.

### PR DESCRIPTION
**Pull request by gep13**
This is being removed from GitHub itself, so we need to remove it from
Cake.Recipe as well.  The upcoming 2.0.0 is the ideal time to put this
through.

Fixes #581

### CODE REVIEW

**Review by AdmiringWorm — APPROVED** [review]
LGTM

**Comment by AdmiringWorm** [comment]
@gep13 I will wait on merging this in until a `GITHUB_TOKEN` variable is added globally on AppVeyor (just so it isn't forgotten).

**Comment by gep13** [comment]
@AdmiringWorm that is a good catch!  I have just added this to the AppVeyor Global Yaml file.

**Comment by AdmiringWorm** [comment]
@gep13 your changes have been merged, thanks for your contribution 👍

**Pull request merged**
