### PR TITLE
Corrected path for transifex user settings

### PR DESCRIPTION
**Pull request by AdmiringWorm**
Once again I found a typo in my code.
Somehow I used the MyDocuments folder path, while in reality it should have been the UserProfile folder path.

I hope I've gotten them all now.

### CODE REVIEW

**Comment by AdmiringWorm** [comment]
I don't understand why appveyor failed this time though.
Let me check first if I need to rebase again

**Comment by gep13** [comment]
@AdmiringWorm I was just typing the same thing 😄

**Comment by AdmiringWorm** [comment]
hmm, everything seems to be up-to-date.
So that isn't the problem this time.
hmm, I don't understand this

**Comment by gep13** [comment]
@AdmiringWorm based on the change, let's merge and see what happens, YOLO :-D

**Comment by AdmiringWorm** [comment]
nope, didn't work. Odd

**Comment by gep13** [comment]
Yip, just looking into it just now...

**Comment by gep13** [comment]
@AdmiringWorm and we are back in business 😄

**Comment by AdmiringWorm** [comment]
yup, I noticed.
I was following the build 😄

**Comment by gep13** [comment]
👍

**Comment by AdmiringWorm** [comment]
and yay, no more errors on my appveyor build as well.
https://ci.appveyor.com/project/cakecontrib/cake-transifex/build/0.5.0-localization.1+10.build.25#L337

Now I feel like I want a 🍺

**Comment by gep13** [comment]
You deserve at least two 😄

**Pull request merged**
