### PR TITLE
version number updates

### PR DESCRIPTION
**Pull request by nmbro**

### CODE REVIEW

**Comment by AdmiringWorm** [comment]
@nmbro a few other that should also be updated would be:
`Cake.Figlet` (Version 1.1.0),
`Cake.Git` (Version 0.17.0)
`Cake.Kudu` (Version 0.7.0)
`Cake.MicrosoftTeams` (Version 0.7.0)
`Cake.Slack` (Version 0.11.0)
`Cake.Transifex` (Version 0.6.0)

The list is currently available in issue #207

**Comment by gep13** [comment]
@nmbro thank you very much for updating this!

I am going to hold off on pulling these in until all the dependencies have been updated. 

Are you in a position to update the list as per @AdmiringWorm suggestion?

**Comment by nmbro** [comment]
I have updated the ones mentioned + cake.wyam. @AdmiringWorm , @gep13

**Comment by gep13** [comment]
@nmbro any chance you can update this PR again?  There have been some more updates.  Thanks!

**Comment by nmbro** [comment]
@gep13 sure what numbers?

**Comment by AdmiringWorm** [comment]
@nmbro the full list is available here: https://github.com/cake-contrib/Cake.Recipe/issues/207

The ones that have been checked now supports Cake 0.26.0+, the only one that doesn't just yet is Cake.Wyam. But it will soon.

**Comment by AdmiringWorm** [comment]
Just one more that I noticed that also needed to be updated:
- The first line in https://github.com/cake-contrib/Cake.Recipe/blob/develop/test.cake

Then I believe everything should be updated.
/cc @nmbro @gep13

**Comment by nmbro** [comment]
I squashed my commits - and added the version numbers to the commit message

**Comment by AdmiringWorm** [comment]
I just tried to take these changes for a test run, and unfortunately they don't work at all.

`Cake.Graph` seems to be the culprit for this though:
```
Could not load [REDACTED]\tools\Addins\Cake.Graph.0.5.0\lib\net46\Cake.Graph.dll (missing RazorEngine, Version=3.10.0.0, Culture=neutral, PublicKeyToken=9ee697374c7e744a)
[REDACTED]/tools/Cake.Recipe.0.3.0-unstable0372/Content/wyam.cake(15,9): error CS0103: The name 'Graph' does not exist in the current context
```

**Comment by nmbro** [comment]
hmm I don't see the RazorEngine being included in the nuget file:
https://github.com/cake-contrib/Cake.Graph/blob/master/nuspec/nuget/Cake.Graph.nuspec

Or the dependency being stated there for that matter.

Could this be the issue?

**Comment by AdmiringWorm** [comment]
@nmbro there is actually quite the few package dependencies that is missing, as well as some .net framework related ones.
https://github.com/cake-contrib/Cake.Graph/blob/master/src/Cake.Graph/Cake.Graph.csproj#L31-L36

**Comment by AdmiringWorm** [comment]
But I think I found out a potential reason it failed for me though, I don't have ASP.NET MVC 6 installed on the computer yet, which I'm guessing the addin requires

**Comment by AdmiringWorm** [comment]
@nmbro I found a workaround for the Cake.Graph failure.
First of all, I also found out it was unrelated to me not having ASP.NET MVC installed,
second it's basically a missing dependency.

However, in the adding if the following is added everything works as expected.
```cs
#addin nuget:?package=RazorEngine&version=3.10.0&loaddependencies=true
```
^^ not completely sure if `&loaddependencies=true` is needed though, didn't test without it.

/cc @gep13

**Comment by AdmiringWorm** [comment]
@nmbro I've actually been running a custom version of Cake.Recipe for some time now, with that dependency added which works great (there's is a problem with gitlink though, but that shouldn't be related to this PR).

**Comment by AdmiringWorm** [comment]
@nmbro BTW, I think perhaps updating the `packages.config` file as well would be appropriate, as the version used already would be incompatible with these changes (I think).

**Comment by gep13** [comment]
@nmbro @AdmiringWorm sorry for the radio silence on this!  Been working on a few things, but I have some time to look at this again.

I am not sure if adding that dependency is the right course of action is it?  Should this not be included in Cake.Graph, rather than here?

**Comment by gep13** [comment]
I think it is time to take this for a spin...

Going to go ahead and get this merged.  I have rebased and merged this locally on my machine, so will close this PR, but the changes have been incorporated.  Thanks!

**Comment by AdmiringWorm** [comment]
@gep13 yeah, I think the correct aproach would be to have the dependency added in `Cake.Graph`, but we wouldn't still be able to use it in Cake.Recipe until it supports Cake `0.28.0` or higher.

**Comment by gep13** [comment]
I have just merged and pushed out a new version of Cake.Graph that supports 0.28.0 :smile:

**Pull request closed without merging**
