### PR TITLE
Check for IsVS2017ProjectFormat when doing publish

### PR DESCRIPTION
**Pull request by mholo65**
Check for IsVS2017ProjectFormat when doing publish, otherwise SDK style projects only targeting full framework won't be published using dotnet publish

### CODE REVIEW

**Comment by gep13** [comment]
I am happy to go with your suggestion here, as I am still a noob when it comes to this stuff.

**Comment by gep13** [comment]
@devlead can you see if this change also fixes the issues that you were seeing?

**Comment by mholo65** [comment]
I.e. should fix publishing .NET SDK style project where the application only targets Full Framework.

**Comment by devlead** [comment]
@gep13 I'll give it a go as soon as I can.

**Comment by devlead** [comment]
@gep13 Tried Cake.Recipe.0.3.0-unstable0364, still get same error. So no.

**Comment by mholo65** [comment]
@devlead, what errors?

**Comment by devlead** [comment]
Same as #200

**Pull request merged**
