### PR TITLE
(GH-738) added resolving of "git.exe"

### PR DESCRIPTION
**Pull request by nils-a**
to all cases of resolving "git" to make them work on windows.

### CODE REVIEW

**Comment by pascalberger** [comment]
Is there a specific reason why https://github.com/cake-contrib/Cake.Recipe/pull/713 is done by calling to git directly and not using Cake.Git / LibGit2Sharp (which already is used in other places)?

/cc @AdmiringWorm

**Comment by nils-a** [comment]
@pascalberger without having done a "deep" check. Is it possible that the `--contains` function is not available in Cake.Git?

**Review by gep13 — APPROVED** [review]
LGTM!

**Comment by gep13** [comment]
@nils-a your changes have been merged, thanks for your contribution 👍

**Comment by AdmiringWorm** [comment]
@pascalberger I don't really remember.
Could be that I just wasn't aware that `Cake.Git` had a way to get the branches, or maybe it was just pulling local branches and ignoring remote ones.

**Comment by gep13** [comment]
@pascalberger there is perhaps an refactoring that can be done here (perhaps to create a function to do this work) however, for now, happy to proceed with this change.

Looking at Cake.Git, it doesn't currently support returning the required information from the call that is being made.

**Pull request merged**
