### PR TITLE
Update Cake.Issues.Recipe to 0.4.2

### PR DESCRIPTION
**Pull request by pascalberger**
Update to [Cake.Issues.Recipe 0.4.2](https://github.com/cake-contrib/Cake.Issues.Recipe/releases/tag/0.4.2) bringing support for GitHub Actions.

### CODE REVIEW

**Review by AdmiringWorm — APPROVED** [review]
LGTM

**Comment by AdmiringWorm** [comment]
@pascalberger your changes have been merged, thanks for your contribution 👍

**Comment by pascalberger** [comment]
New features are shown [here](https://cakeissues.net/news/cake-issues-recipe-v0.4.2-released)

**Comment by gep13** [comment]
Superseded by https://github.com/cake-contrib/Cake.Recipe/pull/690

**Pull request merged**
