### PR TITLE
(maint) Re-enable sourcelink during tests

### PR DESCRIPTION
**Pull request by AdmiringWorm**

### CODE REVIEW

**Comment by gep13** [comment]
@admiringworm based on your successful test, I think this should be ready to go, right?

**Comment by gep13** [comment]
Never mind... we will need to wait for a coverlet release!

**Comment by AdmiringWorm** [comment]
@gep13 I made some changes to the PR to make the adding of SourceLink property conditional, this way we don't have to wait for a new release of coverlet.msbuild for the support to be available in Cake.Recipe

**Comment by gep13** [comment]
@AdmiringWorm great work!

**Pull request merged**
