### PR TITLE
Update Cake.Issues

### PR DESCRIPTION
**Pull request by pascalberger**
Update Cake.Issues to 0.7.x which is build against Cake 0.33.0

### CODE REVIEW

**Comment by Jericho** [comment]
FYI: this will be taken care of automatically by the AddinDiscoverer. When all addins referenced by Cake.Recipe support Cake 0.33.0 the automated tool will submit a PR to upgrade all addins at once and also update the version of Cake used to build Cake.Recipe.

The progress is monitored in #313. As of this writing, two addins are preventing upgrading to 0.33.0: Cake.Graph and Cake.AppVeyor.

**Comment by AdmiringWorm** [comment]
@Jericho Cake.Graph have already been updated to Cake `0.33.0`, so something seems to be wrong here.

It even say so in the Audit docs as well: https://github.com/cake-contrib/Home/blob/master/Audit_for_Cake_0.33.0.md

**Comment by Jericho** [comment]
@AdmiringWorm thanks for pointing this out. I’ll investigate.

**Comment by Jericho** [comment]
@AdmiringWorm the latest version of Cake.Graph nuget package is marked as `prerelease` and the AddinDiscoverer specifically excludes prerelease packages as far as updating the references in Cake.Recipe is concerned. Prerelease packages are not excluded in the markdown report you previously linked.

The reason why this nuget package was flagged as `prerelease` is because it's depending on `RazorLight 2.0.0-beta1` which itself is prerelease.

This explains why the addin is indicated as supporting Cake 0.33.0 in the markdown and Excel reports but it is not considered as supporting Cake 0.33.0 as far as updating Cake.Recipe is considered.

**Comment by Jericho** [comment]
On a separate but related note: this is not the first time that `prerelease` package have caused headaches. I've had several discussions with various people on Gitter and it has come up [here](https://github.com/cake-contrib/Cake.AddinDiscoverer/issues/27#issuecomment-417767998), [here](https://github.com/cake-build/website/issues/535#issuecomment-399707050) and [here](https://github.com/cake-contrib/Cake.Recipe/issues/256#issuecomment-424421249)

I also raised [an issue](https://github.com/cake-contrib/Cake.AddinDiscoverer/issues/52#issuecomment-498763563) a little while ago where I started a discussion about what the AddinDiscoverer should do with prerelease packages. I welcome ideas and feedback.

**Comment by Jericho** [comment]
FYI: new version of AddinDiscoverer has been released and Cake.Graph is now properly considered as "compatible with Cake 0.33.0".

Cake.AppVeyor is now the only addin preventing Cake.Recipe from upgrading to Cake 0.33.0

**Comment by gep13** [comment]
This has been rebased and merged here: https://github.com/cake-contrib/Cake.Recipe/commit/145432b04265818acd837cd50ebe9a50b91f5623

**Pull request closed without merging**
