### PR TITLE
Customization of GitVersionTool version with "CustomGitVersionTool"

### PR DESCRIPTION
**Pull request by larsegholm**
Following suggestion in: https://github.com/cake-contrib/Cake.Recipe/issues/214
I would like to make it possible to customize GitVersion, so I can use GitVersion 4.0.0

### CODE REVIEW

**Comment by skovsende** [comment]
👍 Looks about right.

**Comment by gep13** [comment]
@larsegholm thank you for submitting this PR, I really appreciate it.  Just to make you aware, my main focus just now is updating current known uses of Cake.Recipe (mainly in the Cake-Contrib Organisation) to use a pinned version of Cake.Recipe so that any incoming breaking changes don't affect any upstream callers who aren't pinned to the "released" version.

Once that is done, I plan on looking at merging PR's.

Thanks for your understanding.

This also brings up a larger question on whether all tools should be overridable, and not just one of them.

**Comment by larsegholm** [comment]
@gep13 Np, thanks for the feedback. 
I can work around this for now, so I'll just set this to ready for review in the meanwhile

**Comment by gep13** [comment]
>@larsegholm said...
I can work around this for now, so I'll just set this to ready for review in the meanwhile

Perfect!  Thank you very much!

**Comment by AdmiringWorm** [comment]
> This also brings up a larger question on whether all tools should be overridable, and not just one of them.

Well, why not. But if changing everything to be overridable, why not change every private field to be a public property instead?

Then it would allow users to pretty much set whatever they want.

**Comment by gep13** [comment]
@larsegholm I am going to go ahead and close this PR.  Thank you very much for raising it, but this has been implemented in a slightly different way.  In your recipe/setup.cake file, you should now be able to do somethign like:

```
ToolSettings.SetToolPreprocessorDirectives(gitVersionTool: "#tool nuget:?package=GitVersion.CommandLine&version=5.0.2-beta1.59&prerelease");
```

To control the preprocessor directive for a tool you want to override.

**Comment by skovsende** [comment]
Funnily enough we don't need this hack with the latest 2.0-unstable as GitVersion 5.0.1 works fine for us :)

**Comment by larsegholm** [comment]
True, but in all circumstances; Many thanks for the notice @gep13 !

**Pull request closed without merging**
